version: 0.2

env: 
  secrets-manager: 
    SONAR_TOKEN: "shared/sonarcloud/credentials:SONAR_TOKEN" 


phases:
  build:
    commands:
      - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
