version: 0.2

env: 
  variables:
    SONAR_CLOUD_PROJECT_KEY: "lijumathewrbiz_simple-java-maven-app"
  secrets-manager: 
    JFROG_USERNAME: "shared/jfrog/credentials:JFROG_USERNAME" 
    JFROG_TOKEN: "shared/jfrog/credentials:JFROG_TOKEN"
    SONAR_TOKEN: "shared/sonarcloud/credentials:SONAR_TOKEN"

phases:
  install:
    commands:
       - yum install jq -y 
  pre_build:
    commands:
      - cp -pr jfrog/settings.xml ~/.m2/settings.xml
  build:
    commands:
      - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
  post_build:
    commands:
      - echo "Checking SonarCloud Analysis Status"
      - sleep 10
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$SONAR_CLOUD_PROJECT_KEY >result.json
      - echo $(jq -r '.projectStatus.status' result.json)
      - if [ $(cat result.json | jq -r '.projectStatus.status') = "ERROR" ]; then exit 255; fi
